robo-test:
  app: app/build/outputs/apk/debug/app-debug.apk
  type: robo
  timeout: 10m
  robo-directives:
    "text:input_username": s.salazarc@uniandes.edu.co
    "text:input_password": 123456789156Aa-
  

instrumentation-test:
  type: instrumentation
  app: app/build/outputs/apk/debug/app-debug.apk
  test: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
  use-orchestrator: true
    