name:  SportApp-Grupo1 - Movil - Pull Request - CI

on:
  pull_request:
      branches: [ "main" ]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  test-for-merge:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2.1.2

      - name: Setup java 11
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Build project
        run: ./gradlew build --no-daemon

      - name: Generate code coverage reports
        uses: ReactiveCircus/android-emulator-runner@v2.30.1
        with:
          api-level: 29
          disable-animations: true
          script: ./gradlew testDebugUnitTest connectedDebugAndroidTest testDebugUnitTestCoverage createDebugCoverageReport --stacktrace

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: build-outputs
          path: app/build/outputs