name: SportApp-Grupo1 - Movil - Release - CD

on:
  pull_request:
      branches: [ "main" ]

jobs:
  test-for-relese:
    #if: startsWith(github.ref_name, 'release')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build debug app
        run: ./gradlew assembleDebug 
      - name: Build Android Test APK
        run: ./gradlew assembleAndroidTest
      - name: Setup python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.9'
      - name: Export gcloud related env variable
        run: export CLOUDSDK_PYTHON="/usr/bin/python3"
      - name: GCP Auth
        uses: google-github-actions/auth@v2.1.2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: SetUp GCP Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.1.0
      - name: Set current project
        run: gcloud config set project proyecto2-grupo1
      - name: Run Instrumentation Tests in Firebase Test Lab
        run: gcloud firebase test android run .github/workflow/gcp_android_test_configuration.yaml:instrumentation-test
      - name: Run Robo Tests in Firebase Test Lab
        run: gcloud firebase test android run .github/workflow/gcp_android_test_configuration.yaml:robo-test
      - name: Download artifacts from PR Pipeline
        uses: actions/download-artifact@v4.1.4
        with:
          name: build-outputs
      - name: Create APK Release
        run: bash ./gradlew assemble   
      - name: Create Release
        uses: softprops/action-gh-release@v2.0.4
        with:
          name: SportApp - Grupo 1 - Sprint1
          tag_name: Sprint1
          files: |
            app/build/outputs/apk/release/app-release-unsigned.apk
            build-outputs/build-outputs
            